### ISSUE TITLE
fails to link imported libraries

### ISSUE THREAD

**Issue by bootchk** [Polidea/cmake-nRF5x#3]
Redefinition of CMAKE_CXX_LINK_EXECUTABLE omits <LINK_LIBRARIES>.   It should be:

set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_C_COMPILER} <LINK_FLAGS> <OBJECTS> -lstdc++ -o <TARGET> <LINK_LIBRARIES>")

For example, without it, this fails with undefined references at link time: 

    add_library(bar STATIC IMPORTED)
    set_target_properties( bar PROPERTIES IMPORTED_LOCATION /home/bootch/git/radioSoC/Debug52/bar.a )
    nRF5x_addExecutable(foo main.cpp)
    target_link_libraries( foo bar)

apparently cmake enacts that via <LINK_LIBRARIES>.

Also, what happens if the scripts don't redefine at all (and as you say, CMAKE_C_FLAGS are added implicitly)?  I guess I should try it and see how CMAKE_C_FLAGS disrupt the link.

**Comment by dariuszseweryn** [comment]
With the latest contributions the script is ready for SDK 15 and [has the mentioned definition fixed](https://github.com/Polidea/cmake-nRF5x/blob/5bdbef2acf94cabd23037fdf5fe06c06e3279eaa/CMake_nRF5x.cmake#L98).

I guess I can close this now (after a year...)

Anyway — thank you for the input!

**Comment by CyrilKoe** [comment]
Hi, I am trying to use cmake-nRF5x with C++ but I cannot find any example. Is it possible to compile C++ with it for the nRF5 SDK ? A simple
`add_executable(${CMAKE_PROJECT_NAME}
  "src/main.cpp"
)
`
Doesn't work.
