### ISSUE TITLE
gcc_startup_nrf5 error 

### ISSUE THREAD

**Issue by juttTechnology** [Polidea/cmake-nRF5x#5]
hello,
          I follow your code. and I am using the clion IDE on Mac OS . now I am getting this error. 
```
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:9:157: warning: null character(s) ignored
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:9:169: warning: null character(s) ignored
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o: Assembler messages:
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:1: Error: junk at end of line, first unrecognized character valued 0x7f
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:2: Error: junk at end of line, first unrecognized character valued 0x3
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:3: Error: bad instruction `hh'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:4: Error: bad instruction `c` Hh'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:5: Error: bad instruction `cJ K��'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:5: Error: bad instruction `�x�p����������$'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:6: Error: junk at end of line, first unrecognized character is `:'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:7: Error: junk at end of line, first unrecognized character is `4'
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:8: Error: junk at end of line, first unrecognized character valued 0x1
CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/toolchain/gcc/gcc_startup_nrf51.S.o:9: Error: junk at end of line, first unrecognized character valued 0x7
make[3]: *** [Blinky.out] Error 1
make[2]: *** [CMakeFiles/Blinky.dir/all] Error 2
make[1]: *** [CMakeFiles/Blinky.dir/rule] Error 2
make: *** [Blinky] Error 2
```

in the start he give me lot of warning but I just copy last two warning which is the same as previous warning. after then some error regarding the gcc_startup_nrf5.

thank you

**Comment by dariuszseweryn** [comment]
Hello,
It seems that you have some problem in the sdk you have downloaded. Maybe it is corrupted or not the one this cmake file is intended to use (`12.3.0`)

**Comment by juttTechnology** [comment]
now I am using the 12.3.0 version which fix this issue 
but now I have this problem which is relevant to this define 
 #define TIMESTAMP_STR(val) "[%0" NUM_TO_STR(val) "d]"
in the  nrf_log_backend_serial.c 
do I need to change some flags or something else 


/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Users/atifshabbir/Development/git/Blinky/cmake-build-default --target Blinky -- -j 2
Scanning dependencies of target Blinky
[  7%] Building C object CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_frontend.c.o
[  7%] Building C object CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c.o
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c: In function 'timestamp_process':
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:42:28: error: unknown conversion type character 'N' in format [-Werror=format=]
 #define TIMESTAMP_STR(val) "[%0" NUM_TO_STR(val) "d]"
                            ^
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:211:71: note: in expansion of macro 'TIMESTAMP_STR'
         len = snprintf(&p_str[len],NRF_LOG_BACKEND_MAX_STRING_LENGTH, TIMESTAMP_STR(NRF_LOG_TIMESTAMP_DIGITS), (int)*p_timestamp);
                                                                       ^~~~~~~~~~~~~
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:42:28: error: too many arguments for format [-Werror=format-extra-args]
 #define TIMESTAMP_STR(val) "[%0" NUM_TO_STR(val) "d]"
                            ^
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:211:71: note: in expansion of macro 'TIMESTAMP_STR'
         len = snprintf(&p_str[len],NRF_LOG_BACKEND_MAX_STRING_LENGTH, TIMESTAMP_STR(NRF_LOG_TIMESTAMP_DIGITS), (int)*p_timestamp);
                                                                       ^~~~~~~~~~~~~
In file included from /Users/atifshabbir/Development/SDK/components/libraries/util/sdk_common.h:34:0,
                 from /Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_frontend.c:12:
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_frontend.c:23:16: error: 'NRF_LOG_DEFERRED_BUFSIZE' undeclared here (not in a function); did you mean 'NRF_LOG_DEFERRED'?
 STATIC_ASSERT((NRF_LOG_DEFERRED_BUFSIZE == 0) || IS_POWER_OF_TWO(NRF_LOG_DEFERRED_BUFSIZE));
                ^
/Users/atifshabbir/Development/SDK/components/libraries/util/app_util.h:110:64: note: in definition of macro 'STATIC_ASSERT_MSG'
         ;enum { STRING_CONCATENATE(MSG, __COUNTER__) = 1 / (!!(EXPR)) }
                                                                ^~~~
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_frontend.c:23:1: note: in expansion of macro 'STATIC_ASSERT'
 STATIC_ASSERT((NRF_LOG_DEFERRED_BUFSIZE == 0) || IS_POWER_OF_TWO(NRF_LOG_DEFERRED_BUFSIZE));
 ^~~~~~~~~~~~~
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c: In function 'nrf_log_backend_serial_hexdump_handler':
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:355:13: error: 'NRF_LOG_TIMESTAMP_DIGITS' undeclared (first use in this function); did you mean 'NRF_LOG_INTERNAL_INIT'?
             NRF_LOG_TIMESTAMP_DIGITS+2 : 0; //+2 since timestamp is in brackets
             ^~~~~~~~~~~~~~~~~~~~~~~~
             NRF_LOG_INTERNAL_INIT
/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c:355:13: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors
make[3]: *** [CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_backend_serial.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/Blinky.dir/Users/atifshabbir/Development/SDK/components/libraries/log/src/nrf_log_frontend.c.o] Error 1
make[2]: *** [CMakeFiles/Blinky.dir/all] Error 2
make[1]: *** [CMakeFiles/Blinky.dir/rule] Error 2
make: *** [Blinky] Error 2

**Comment by dariuszseweryn** [comment]
Maybe you are using an old version of the toolchain?

**Comment by juttTechnology** [comment]
no I am using tool chain version 7

now compilation have no issue but linking have some problem 
where you are linking main.cpp in the cmake 

/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Users/atifshabbir/Development/git/Blinky/cmake-build-default --target Blinky -- -j 2
[  3%] Linking C executable Blinky.out
/Users/atifshabbir/Development/ToolChain/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/crt0.o: In function `_start':
(.text+0x4a): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [Blinky.out] Error 1
make[2]: *** [CMakeFiles/Blinky.dir/all] Error 2
make[1]: *** [CMakeFiles/Blinky.dir/rule] Error 2
make: *** [Blinky] Error 2

**Comment by dariuszseweryn** [comment]
In `CMakeLists.txt`:
```
list(APPEND SDK_SOURCE_FILES
  "${PROJECT_SOURCE_DIR}/main.c"
)
```

**Comment by dariuszseweryn** [comment]
It seems that there is no problem with the `CMake_nRF5x.cmake` itself. Unfortunately I am no expert in setting up the compilation

**Comment by juttTechnology** [comment]
no problem. I fix this issue and now everything is ok. I will try to run this solution with new sdk, I think this will not be big issue
