### ISSUE TITLE
TOOLCHAIN_PREFIX should be configurable

### ISSUE THREAD

**Issue by ildar** [Polidea/cmake-nRF5x#61]
i.e. defined as a variable to be used in command line:
> cmake -D TOOLCHAIN_PREFIX=/usr ...

**Comment by borys-jelenski-polidea** [comment]
Well, actually you MUST specify it like this when calling CMake. Why doesn't it work for you?

**Comment by ildar** [comment]
Sorry, at some point of my experiments cmake said it would ignore
TOOLCHAIN_PREFIX.
But with CMAKE_TOOLCHAIN_FILE it got allright.
So that was misuse. Thanks.
