### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by cerealkill** [Polidea/cmake-nRF5x#7]
I followed the example, it compiles, flashes both softdevice and firmware, but the Led1 that is supposed to be lit on the board is not and the ble is not broadcasting.

I also compiled the simple `peripheral/blinky` example and it also does not work. 

Am I missing something?

Thank you

**Comment by dariuszseweryn** [comment]
> Am I missing something?

I do not know — you have not described what exactly what gcc/sdk you use, what nRF chip. If the code compiled (which you said it did) then the problem seem to be outside of CMAKE.

**Comment by cerealkill** [comment]
Thanks for the feedback, it was my mistake regarding the target board and compilation flags. I added more automation to add support to `pca10056` and created a pull request. It would be nice if ppl added more examples and test on more devkits. I am working on the former.
https://github.com/Polidea/cmake-nRF5x/pull/8
